### ISSUE TITLE
Bug with deploying with priceIdentifier BTCUSD on Kovan

### ISSUE THREAD

**Issue by dim3003** [UMAprotocol/launch-lsp#20]
I encountered an issue when trying to launch on Kovan network with BTCUSD as price identifier. It created a VM execution error.

My launch script:

`node index.js 
--gasprice 15 
--url wss://kovan.infura.io/ws/v3/PROJECTIDInfura
--mnemonic "SEED PHRASE"
--pairName "WHTUSDJune" 
--expirationTimestamp 1655312460 
--collateralPerPair 1000000000 
--priceIdentifier BTCUSD 
--longSynthName "wheat_SRW_June_long" 
--longSynthSymbol WHTUSDBJun 
--shortSynthName "wheat_SRW_June_short" 
--shortSynthSymbol WHTUSDSJun 
--collateralToken 0x7079f3762805cff9c979a5bdc6f5648bcfee76c8 
--fpl Linear 
--lowerBound 0 
--upperBound 2000000000 
--proposerReward 2000000 
--optimisticOracleProposerBond 200000000 `

The error I get:

`Error: VM execution error.
    at WebsocketSubprovider._handleSocketMessage (C:\Users\FOLDER\launch-lsp\node_modules\@trufflesuite\web3-provider-engine\subproviders\websocket.js:121:18)
    at WebSocket.onMessage (C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\websocket.js:720:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\receiver.js:414:14)
    at C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\receiver.js:371:23
    at C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\permessage-deflate.js:307:9
    at C:\Users\FOLDER\launch-lsp\node_modules\ws\lib\permessage-deflate.js:389:7
    at afterWrite (_stream_writable.js:468:5)
    at onwrite (_stream_writable.js:448:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:580:8) `

Changed the price identifier to UMAUSD and it worked. Still do not know what went wrong though.

**Comment by jiivii252** [comment]
Help
